In [1]:
import numpy as np
import os

In [2]:
from time import sleep, perf_counter
from threading import Thread
from threading import Lock

In [3]:
x = np.array([[9, 2, 3], [4, 5, 6]], np.int32)

In [4]:
print(x[1, 2])

6


In [5]:
np.savetxt("test.txt", x)

In [6]:
y = np.loadtxt("test.txt")

In [7]:
print(y)

[[9. 2. 3.]
 [4. 5. 6.]]


In [8]:
print(y[0][0])

9.0


In [9]:
if(y[0][0] == 1):
    print("found something")
else:
    print("found nothing")

found nothing


In [10]:
z = np.random.randint(0, 1, size=(6,14))

In [11]:
print(z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [12]:
runner = 0
for y, x in np.ndindex(z.shape):
    runner +=1
    if runner % 2:
        z[y][x] = 1
    elif runner % 4:
        z[y][x] = 2


In [13]:
print(z)

[[1 2 1 0 1 2 1 0 1 2 1 0 1 2]
 [1 0 1 2 1 0 1 2 1 0 1 2 1 0]
 [1 2 1 0 1 2 1 0 1 2 1 0 1 2]
 [1 0 1 2 1 0 1 2 1 0 1 2 1 0]
 [1 2 1 0 1 2 1 0 1 2 1 0 1 2]
 [1 0 1 2 1 0 1 2 1 0 1 2 1 0]]


In [14]:
dirname = os.path.dirname(os.getcwd())
print(dirname)
filename = os.path.join(dirname, "python/myArena.txt")
print(filename)
np.savetxt(filename, z)
    

/Users/shenkler/sciebo/work/Nebentätigkeit/ESM/teaching/22/MSE
/Users/shenkler/sciebo/work/Nebentätigkeit/ESM/teaching/22/MSE/python/myArena.txt


In [15]:
loadedArena = np.loadtxt(filename)

In [16]:
print(loadedArena)

[[1. 2. 1. 0. 1. 2. 1. 0. 1. 2. 1. 0. 1. 2.]
 [1. 0. 1. 2. 1. 0. 1. 2. 1. 0. 1. 2. 1. 0.]
 [1. 2. 1. 0. 1. 2. 1. 0. 1. 2. 1. 0. 1. 2.]
 [1. 0. 1. 2. 1. 0. 1. 2. 1. 0. 1. 2. 1. 0.]
 [1. 2. 1. 0. 1. 2. 1. 0. 1. 2. 1. 0. 1. 2.]
 [1. 0. 1. 2. 1. 0. 1. 2. 1. 0. 1. 2. 1. 0.]]


In [17]:
def task(id):
    print('Starting a task...')
    print(id)
    if id==1:
        sleep(5)
    elif id==2:
        sleep(1)
    print(f'done {id}')

In [18]:
def task2(lock, id):
    with lock:
        print('Starting a task...')
        print(id)
        if id==1:
            sleep(5)
        elif id==2:
            sleep(1)
        print(f'done {id}')

In [19]:
start_time = perf_counter()

In [20]:
t1 = Thread(target=task,args=(1,))
t2 = Thread(target=task, args=(2,))

In [21]:
t1.start()
t2.start()

Starting a task...Starting a task...
1

2
done 2
done 1


In [22]:
t1.join()
t2.join()

In [23]:
end_time = perf_counter()

In [24]:
print(f'It took {end_time- start_time: 0.2f} second(s) to complete.')

It took  77.63 second(s) to complete.


In [25]:
lock = Lock()
t1 = Thread(target=task2,args=(lock,1,))
t2 = Thread(target=task2, args=(lock,2,))
t1.start()
t2.start()
t1.join()
t2.join()

Starting a task...
1
done 1
Starting a task...
2
done 2
